FROM node:20-alpine

WORKDIR /app

COPY . .
RUN npm install

# --- TAMBAHKAN DUA BARIS INI ---
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
# -------------------------------

# Build aplikasi Web (Sekarang Next.js akan menanamkan URL dari ARG ke dalam bundle)
RUN cd apps/web && npm run build

# Ekspos port Next.js
EXPOSE 3000

# Jalankan aplikasi Web
CMD ["sh", "-c", "cd apps/web && npm run start"]